version: '3.1'

services:

  camagru:
    build: docker
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/myapp
    working_dir: /usr/src/myapp/
    command: php -S 0.0.0.0:8000 -t ./dist
